### ISSUE TITLE
xDhcpClient doesn't set DNS servers back to DHCP

### ISSUE THREAD

**Issue by gmatusko** [PowerShell/xNetworking#113]
It would be great if xDhcpClient checked if DNS settings for an adapter were set to "Obtain DNS server address automatically".  Right now it only checks for IP settings and I'd like to switch DNS settings back to DCHP as well.  Let me know if this is a reasonable request.

Greg

**Comment by PlagueHO** [comment]
Hi @gmatusko 

A great point (and needed feature). It would actually need to be implemented in the xDNSServerAddress resource because to reset the DNS Client back to using DHCP settings you actually issue:
```powershell
Set-DnsClientServerAddress -ResetServerAddresses -InterfaceAlias Ethernet
```
If we added this in DHCP client then there would be a risk of a config that was conterminously reapplied.

At first I thought this would be relatively easy, but it isn't quite so straight forward.

One way of doing this would be to allow the Address property to accept a $null value. If $null is set then the Resource should ensure that the DNS client is set to DHCP mode. However, I can't find a way of identifying if the DNS client is currently set to DHCP mode or not. I'll need to do some more digging about on this.

**Comment by PlagueHO** [comment]
I'll revisit this one this weekend and see if I can't figure out a solution.

**Comment by andy1547** [comment]
In this case of switching from static to DHCP it should only reset back to automatic if no primary/secondary DNS is supplied, as it's possible to use both DHCP and a manual DNS server address.

**Comment by PlagueHO** [comment]
Thanks @andy1547 !

As I mentioned a while back, the solution wouldn't be to change xDHCPClient, but to change xDNSServerAddress so that it allowed a blank list of addresses - which would cause
```powershell
Set-DnsClientServerAddress -ResetServerAddresses -InterfaceAlias Ethernet
```
to be called when the DNS client server addresses need to be changed back to DHCP.

**However there is one very major problem:**
In PowerShell there is no way to detect if the DNS Server Addresses assigned to an adapter were assigned as static or are DHCP assigned - so the DNS Client that was to be configured as being DHCP assigned will constantly be reported as not "in state" and will be continuously be reset to DHCP.

For example, if you run:
```powershell
Get-DnsClientServerAddress -AddressFamily IPv4 | fl *
```

you will see the information about the DNS Client server addresses - but you are not able to tell if the addresses in the ServerAddresses property are assigned via DHCP or not. So we can't tell if the resource is in state or not - which will result in continuously resetting the DNS Server Addresses - which will likely cause connectivity issues every time the config is applied.

So I think the only solution is to be able to figure out if the DNS Server Addresses are set with DHCP or not - which will require some changes to PowerShell Net Client.

Does that make sense?

**Comment by andy1547** [comment]
@PlagueHO 
I agree with you that it should be part of xDNSServerAddress not xDhcpClient.

The dynamically returned DNS IPs I've have I battled the same problem in my custom script resource and have came up with a great solution which I've described below.

The scenario you described happens both when the DNS is automatic or manual yet blank (sometimes mine would be 192.168.1.1, other times blank). This registry being null or empty holds the answer
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\\{Network_Adaptor_GUID}\NameServer`

When null or empty this flag would indicate that the DNS addresses returned may potentially be dynamically generated, therefore instead of returning them to be compared (which is pointless) you can return an empty list of IPs.

If the desired configuration of xDNSServerAddress IPs are empty, we have a match and we should not call set. If the configuration of xDNSServerAddress Ips are not empty, then the static IPs will be set.
When this flag is false (the IPs returned from the NIC are statically set) we simply return them and compare with what the desired configuration is.
Moreover, the decision in the SetResource to call either reset or set static should be based on whether the desired configuration DNS IP array is empty or not.

Hope that clears things up, you could combine DHCP enabled check with this flag to determine the difference between automatic and manual yet empty but this is not required as if DHCP is enabled and the DNS is blank windows will always force it back to automatic.

**Comment by PlagueHO** [comment]
Hi @andy1547 - that is some great info.

I would definitely prefer to use native cmdlets rather than the registry for this, but in the absence of the cmdlets I should be able to make your suggestion work. The plan would definitely to try and only make changes to xDNSServerAddress resource as that would be the safest solution.

Let me see what I can do.

**Comment by PlagueHO** [comment]
I'm working on this now and aim to have it completed by the end of today.
