### ISSUE TITLE
xFirewall throws error when correcting Profile changes

### ISSUE THREAD

**Issue by RamonPalmieri** [PowerShell/xNetworking#140]
Hi,

On windows2k12/WMF5.0 I found an issue.
When I create a firewall rule with DSC and later on change the profile settings xFirewall throws an error:

Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Set-NetFirewallRule
    + PSComputerName        : localhost

Original resource setting:
        xFirewall AllowRDP
        {
            Name = 'Remote Desktop Admin Connections'
            DisplayName = 'Remote Desktop Admin Connections'
            Group = "DSC - Remote Desktop"
            Ensure = 'Present'
            Enabled = 'True'
            Action = 'Allow'
            **_Profile = 'Domain', 'Private', 'Public'_**
        }

Changed resource settings:
        xFirewall AllowRDP
        {
            Name = 'Remote Desktop Admin Connections'
            DisplayName = 'Remote Desktop Admin Connections'
            Group = "DSC - Remote Desktop"
            Ensure = 'Present'
            Enabled = 'True'
            Action = 'Allow'
            **_Profile = 'Domain', 'Private'_**
        }

This error also occurs when changing profile settings by GUI and letting DSC correct it.

Greetings,

Ramon.

**Comment by PlagueHO** [comment]
Hi @RamonPalmieri - thanks for reporting this. I actually think this is actually the same cause as this issue: https://github.com/PowerShell/xNetworking/issues/130

We haven't come up with a perfect solution to this problem yet. However, if you remove the ```Group``` parameter from your xFirewall configuration they should work fine.

**Comment by RamonPalmieri** [comment]
I removed the Group parameter and it works fine!
Thanks.

**Comment by Byte-666** [comment]
Wouldn't it work if you just removed "group" like that https://github.com/Byte-666/xNetworking/commit/dbd598e3094b87e3aba6e7e96dd0626be43b3f1b ?

**Comment by PlagueHO** [comment]
@Byte-666 - Unfortunately I don't think so. Because in this case the error is actually occurring in a different part of the code. Specifically this line: https://github.com/Byte-666/xNetworking/commit/dbd598e3094b87e3aba6e7e96dd0626be43b3f1b#diff-7cd1710b844d68d1e0e70b8edd3736d3R451

It is the call to `Set-NetFirewallRule` that causes the problem in this case. The problem is that the `Set-NetFirewallRule` cmdlet only supports the `Group` parameter as an identifier for the rule(s) that needs to be changed. But in our case we want to update the `Group` value for the rules matching the `Name` parameter.

I raised this as a UserVoice issue some time ago, but I doubt it's a high priority one.
