### ISSUE TITLE
SubnetMask vs. PrefixLength

### ISSUE THREAD

**Issue by barcexwiki** [PowerShell/xNetworking#145]
I suggest to use a 'PrefixLength' parameter instead of 'SubnetMask'. A subnet mask is a 4-octect value (like 255.255.255.0) while the prefix length is an integer (from 0 to 32 for IPv4 and from 0 to 128 for IPv6). 
The current naming is confusing because the SubnetMask parameter expects a prefix length and not a subnet mask.
Getting rid of subnet masks in favor of prefix lengths is also good as subnet masks are a thing of the past in IP routing.

**Comment by PlagueHO** [comment]
@barcexwiki - I fully agree with you. But because this would be a breaking change it should be discussed further.

One suggestion I have is that if the xnetworking resource is going to be moved over to HQRM, this change could be done as part of that - HQRM will result in a breaking change anyway. 

@travisez13, @kwirkykat?

**Comment by TravisEz13** [comment]
I think we should do the change.  I don't see the point of delaying it.

**Comment by PlagueHO** [comment]
@TravisEz13 - cool. Fair enough. I'm happy to make the change for inclusion into the next release if you like?

**Comment by PlagueHO** [comment]
Working on this now. Should submit the PR later today.
