### ISSUE TITLE
xFirewall is not compatible with Windows 7 or 2008

### ISSUE THREAD

**Issue by richard-browne** [PowerShell/xNetworking#156]
The term 'Get-NetFirewallRule' is not recognized as the name of a cmdlet, function, script file, or operable program.

:-(

**Comment by PlagueHO** [comment]
Hi @richard-browne - you are quite correct.

This was raised a while back in [this issue](https://github.com/PowerShell/xNetworking/issues/30).

We looked into it then and decided it would be too difficult and unreliable to retrofit the resources to work with these older OS's. Besides that, these OS's (at least Windows Server 2008) have all passed the [mainstream support end date](https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%20Server%202008).

@kwirkykat - does the Micrsosoft PowerShell team have any thoughts on this?

Sorry I haven't been able to provide more help :cry:

**Comment by kwirkykat** [comment]
@richard-browne What WMF/PS version are you running?

**Comment by richard-browne** [comment]
@kwirkykat I'm using WMF 5.0 on Windows 7.

PSVersion 5.0.10586.117.

**Comment by PlagueHO** [comment]
@kwirkykat - The problem is with the OS rather than the version of WMF5.0. The Net* cmdlets weren't added to the OS till Windows Server 2012/Windows 8 (I could be wrong about the specific version, but they definitely weren't in WS2008).

So running on any older OS's would require us creating our own Net* cmdlet functionality in the DSC resource either using WMI/CIM or calls to NETSH - even if WMF4.0, WMF5.0 or WMF5.1 is installed. I did some investigation last year and did find it would probably be possible though, but a fairly big job that would increase the amount of code/tests/complexity significantly.

**Comment by kilasuit** [comment]
As @PlagueHO mention they were added in as part of Win8 & Server 2012 due to the changes in the OS that allowed/instigated these to be developed much easier than for the prior OS's (Win7 & Server 2008R2)

Personally Win7 & Server 2008R2 support with any of the DSC Resources should be categorised on a "best endeavours" basis but then again for the Systems that would be deployed on those OS's (SharePoint 2010 being one that comes to mind) have in other resources been ruled out of scope for DSC as they don't support WMF4

If possible it would be good to understand the Scenario that you are looking at using DSC for on these OS's so that we could either 

1. Add the functionality to this resource module
1. Suggest a slightly different path
1. Fork this and build only 2008/Win7 Functionality to reduce the long term tech debt that will come with supporting 2008/Win7

I know that doesn't immediately solve this but hopefully gives you good background behind why we are where we currently are at with this resource module.

**Comment by kwirkykat** [comment]
@PlagueHO 
You are correct that these cmdlets weren't available until Windows 8/Server 2012. DSC itself wasn't even available until Windows 8.1/Server 2012 R2. On top of that even, this is an unsupported DSC Resource Kit module.
So this definitely doesn't require a change to the resource in question. I'm just curious if there's any way he could work around it on an earlier OS.

This 'minimum version' info should be added to the README.

@richard-browne 
My best guess based on all the older questions and answers I've seen about this is that this can't be done, but you may be able to at least try some things out.

If you go to ```C:\Windows\System32\WindowsPowerShell\v1.0\Modules``` on your machine does the NetSecurity module exist there? That's the module that would have the command in question.

If it does exist, then can you import it or does it throw a parse error? Can you call any of the commands from the module or do they throw an error?

If it does not originally exist on the machine, could you get it from a different machine that has it (Windows 8/Server 2012 and above) and try just copy and pasting it in that folder? Maybe you could import it as a 'custom' module then?

I'm doubtful this would work. The cmdlets may or may not require you to [update your version of .NET](https://msdn.microsoft.com/en-us/library/5a4x27ek(v=vs.110).aspx) as well.

**Comment by richard-browne** [comment]
It's understandable that xNetworking is focused on Win8/2012. The problem for many of us is that the majority of Windows servers are still running Server 2003/2008/2008R2. That makes xNetworking not so useful today.

Anyhoo for others that arrive here with this issue I found the LegacyNetworking module. It has a vFirewall resource that works on Win7/2008R2:

 https://github.com/VirtualEngine/LegacyNetworking

**Comment by iainbrighton** [comment]
@richard-browne Thie is why I put https://github.com/virtualengine/legacynetworking together.

It doesn't have anywhere near complete coverage as it only does what we need it to. However, it does have a matching schema where possible and might get you out of a hole?

**Comment by iainbrighton** [comment]
This is why I put https://github.com/VirtualEngine/LegacyNetworking<https://github.com/VirtualEngine/LegacyNetworking/blob/master/README.md>/ together. It's not complete coverage, but it does try to match the xNetworking schema where possible.

It only does what we need it to do as I didn't want to put too much effort in. However, it might be a good start point and get you out of a hole?
