### ISSUE TITLE
Create NetConnectionProfile resource

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#19]
I'm thinking we should create a NetConnecitonProfile resource. This would allow the management of the NetworkCategories  of Private/Public/Domain etc on the interface level. This would also mean pulling it it out of xIPAddress which would solve #3 by doing this.

Before doing this work I wanted to ask the community their thoughts on the design.

Thanks!

**Comment by Dan1el42** [comment]
Great idea :-). I actually have a draft of an DSC resource call xNetConnectionProfile on my cloud drive.

The basic design I would like to propose is:

Get/Set/Test-TargetResource invoke internal functions Get/Set/Test-NetConnectionProfileInternal which invoke the Get/Set-NetConnectionProfile functions of the PowerShell module included with each OS with some additional logic and verbose logging.

I think the advantages of the internal functions are easier debugging and testing without the LCM, and the ability to use the internal functions in a future versions of the resource module with a DscResource class instead.

Get/Set/Test-TargetResource do not need extensive tests because each contains basically one line of code splatting the parameters to the internal functions and returning an object if applicable. The primary testing would be happening on the internal functions with mocks for Get/Set-NetConnectionProfile functions for Unit tests.

Thoughts?

P.S. I think I can make the time this coming Saturday to complete the resource and submit it as pull request.

Best,
Daniel

**Comment by tysonjhayes** [comment]
I'm not really a fan of internal functions unless they serve a good purpose, just my opinion really, just seems an unnecessary level of complexity when the three primary funcitons work just as well. However, I can appreciate the thought process behind the idea and will withold judgement until I can actually see it. :grinning: 

If you have time this Saturday to take a crack at it I'd love to see it!

**Comment by iainbrighton** [comment]
FYI - I created this a while ago https://github.com/iainbrighton/cNetworkProfile. I'm happy for it to be developed further, merged into another repo or completely ignored. Some of the code might help?

**Comment by Dan1el42** [comment]
@iainbrighton, Thanks for the pointer. I will checkout your resources and look into how we can merge them.
