### ISSUE TITLE
xFirewall - Ability to disable a profiles

### ISSUE THREAD

**Issue by TraGicCode** [PowerShell/xNetworking#249]
How come there is no feature to the firewall profiles?  This would be helpful for those who want to use a third party firewall.  Any reason why this isn't implemented yet?

**Comment by tysonjhayes** [comment]
Hi @TraGicCode most of this is written in the maintainers spare time, myself included, so likely we haven't had a need or a scenario come up yet that this type of functionality would be needed. We welcome pull requests if this is something you'd like to implement. Otherwise when someone has time to look into this we will try our best.

If you could outline, what you are looking for, desired outcome, and some example commands it'll assist this request getting done quicker.

**Comment by PlagueHO** [comment]
This was mentioned over here in [this issue](https://github.com/PowerShell/xNetworking/issues/218). There was a possibility of that being ported across. However, as this hasn't happened yet, I'll get this done now.

**Comment by PlagueHO** [comment]
I've completed this one now. It will still need to be reviewed and merged.

If you want to try it out, you can find it here:
https://github.com/PlagueHO/xNetworking/tree/Issue-249
