### ISSUE TITLE
xIPAddress resource currently incompatible with Windows Server 2008 R2

### ISSUE THREAD

**Issue by bgshacklett** [PowerShell/xNetworking#30]
There are multiple calls to networking cmdlets like Get-NetIPAddress, Get-NetRoute and Get-NetIPInterface, specifically in the Test-TargetResource function. These cmdlets are unavailable on Windows Server 2008 R2, making it impossible to use this

**Comment by tysonjhayes** [comment]
I've been thinking about this and, in my opinion I'm not sure this is really in scope for xNetworking. Making this system backwards compatiable to 2008 R2 would represent quite a bit of work as it does lack a number of PowerShell commands that were introduced in later versions. Not to mention most of the resources that are being added are assuming that they have access to those cmdlets. I also wouldn't want to make just the xIPAddress backwards compatiable if we wanted to take on support of that OS I would want everything to be able to support it.

Again this is just my opinion if there is a significant push for this I'm open to a PR on it.

**Comment by PlagueHO** [comment]
My 2c: I agree with @tysonjhayes. I'd also add that implementing this would require either calling NETSH commands and then parsing the results back into PS Objects or possibly using WMI/CIM, both solutions don't seem to be ideal. And NETSH has been deprecated in Windows Server 2012 R2 and above, so that would mean supporting multiple code paths depending on the system version.

**Comment by tysonjhayes** [comment]
I'm going to close this issue as there hasn't been any discussion on this since October. You are welcome to reopen this if you want to continue discussing it.
