### ISSUE TITLE
xDnsServerAddress fails if DNS server is not reachable

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xNetworking#39]
In the later versions of the xDnsServerAddress resource, the `-Validate` switch has been added to the `Set-DnsClientServerAddress` cmdlet. If this address is not contactable, unavailable or unreachable etc., then the DSC configuration fails.

This call should be removed as the resource is not there to validate whether the DNS server is (yet) available, reachable or contactable - it should just do what it's told!

**Comment by PlagueHO** [comment]
So basically, get rid of the -validate parameter on the Set-DnsClientServerAddress cmdlet? Can you clarify this? I'm not sure which resource might not yet be available, reachable or contactable? Are you meaning the resource on another server that creates/configures the DNS Server/Zone etc? In that case I'm actually 100% with you there and have run into similar situations (but worked around it by using the WaitFor resource to wait for the DNS Server to be created - not ideal though).

@tysonjhayes, what do you think on this one? I see the point in removing it and have had situations where it caused problems.

**Comment by iainbrighton** [comment]
Correct - when provisioning a lab/text environment, this resource now fails _unless_ the DNS server is available, up-and-running and responding during the configuration pass. Simply removing line 105 in the xDnsServerAddress.psm1 file fixes the issue!

@tysonjhayes - IMHO the configuration and state of the DNS server are of no concern to the client!

**Comment by PlagueHO** [comment]
The same issue has been raised in #36. @amitsara has suggested adding a **validate** parameter that defaults to $false and could be set to $true if validatation was required when setting the resource.

But I am straining to find a purpose to keep validation in at all TBH - and removing it would certainly be easier :)

**Comment by PlagueHO** [comment]
I'm on the delete side as well. Just would like to hear from @tysonjhayes on it as we did do away in a recent PR but I think I remember he suggested it get added back, so there might be a reason for it being in there.

**Comment by tysonjhayes** [comment]
Geez, guy goes to lunch and his inbox blows up as he's beeing name checked in a couple of issues. :laughing: 

Let me start by saying I can be persuaded either way here.

1) The value to me in the validate is simply that, to validate that the DNS is responding as expected. Which I saw value in some scenarios as I didn't really imagine setting DNS without having the DNS I'm setting online, but I'm human and can't always see all angles of things.

2) If the community doesn't see the value at all then yes let's remove it all together. However I would argue that adding a switch to the configuration would allow the best of both worlds for those who really don't want to change the DNS if it's not responding, I'm thinking production scenarios where we could accidently take a server down if the DNS is not online during the switch, or pull scenarios where I've pushed the config to the wrong set of machines. So I think adding a switch to the configuration as @PlagueHO suggested.

Also I would encourage us not to shy away from things because they are hard we should do things because they are the right thing to do.

**Comment by iainbrighton** [comment]
Lunch? Who said you could go during our hour of need?! :P

I think I've made my views clear! In short, as long as there's a way of turning the -Validate option off then I'll be happy.

**Comment by PlagueHO** [comment]
What are you talking about? It's barely breakfast here. On Friday. :)

Ok. Lets go with the validate option. Works for me - it's fairly easy either way. I can put it together later on today if you like?

Any thoughts on what the default value should be? I'm really 50/50 on it TBH.

**Comment by tysonjhayes** [comment]
Oh $false without a doubt. Personally hate it when boolean/switches are set to true by default. Super confusing, and from the issues would cause more impact anyway.

Also not all of us are lucky enough to live in Kiwi future. Pffft. :stuck_out_tongue_closed_eyes: 

Also yes if you would be so kind :+1:

**Comment by PlagueHO** [comment]
Cool! Decision made :+1:

I'll get it through later on today.

Also, I'm sure there's an applicable "back to the future" joke in there too somehow...? :)

**Comment by tysonjhayes** [comment]
@iainbrighton we merged the change to try to fix this. Could you confirm you're now unblocked?

**Comment by iainbrighton** [comment]
Excellent =). I will try and test today..

**Comment by iainbrighton** [comment]
@tysonjhayes @PlagueHO  I can confirm that the latest dev branch fixes my problem. Thank guys!

**Comment by PlagueHO** [comment]
Cool! :+1:

**Comment by tysonjhayes** [comment]
Fantastic. Thanks @iainbrighton

**Comment by amitsara** [comment]
Thanks :+1:
