### ISSUE TITLE
Add Integration Template to Project

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#45]
Add a template of how we want Integration tests to be done in this project. Once we have a few of them we should add the template to other projects in the PowerShell group.

Template should outline how we expect the tests to act and where to copy things for maximum compatibility.

**Comment by PlagueHO** [comment]
One thing I ran into is that I didn't have script execution set to Unrestricted so the integration tests failed on my test box. This isn't the case on AppVeyor (which is why it passes just fine). 

So we'll want to Set this to unrestricted before running the integration tests and then set it back to what it was at the end.

I'll include this in the PR for Issue #44.

**Comment by PlagueHO** [comment]
Another idea for this is that the Header/Footer for the **Unit tests** should also go in with these templates.

I've noticed that the Unit Test and Integration Test header/footers are almost identical in function (the only difference is which module to load). So in my latest changes (for Issue #47 ) I've changed the Header and Footer of both Unit and Integration tests so they are identical except for the first three lines which just contain the module names and relative paths. Perhaps you could take a look at this when I submit the PR and give me your thoughts? 

Also, I'm using some form of this code in every module I work on, but it's often slightly different (because of when I copied or pasted it etc) - which causes all sorts of testing headaches. So, I think Ideally at some point all of this header/footer code should go into some helper module (like DSCResource.tests/HelperTests.psm1 - because that code is already pulled in most AppVeyor configs). I think we should try and avoid code repetition as much as possible. But that discussion could be left for another date.

Right, back to it!

Cheers

**Comment by KarolKaczmarek** [comment]
That's a great idea! Please send the PR into DscResource.Tests repo once you're ready.

I also agree template for Unit tests would be helpful as well to have a proper setup/cleanup in place.

**Comment by PlagueHO** [comment]
Cool! Once we've finalized the Unit/Integration tests headers/footers I'll look at moving them into TestHelpers.psm1 :+1:

In PR #52 I've managed to synchronize the Header/Footer code for both Unit and Integration tests, so we should only need a single Start-TestFramework/Stop-TestFramework that will work for either. Not really sure of the right verbs to use here though.

**Comment by tysonjhayes** [comment]
Going to close this one as we have the templates in this resource, getting them broadly will be up to https://github.com/PowerShell/DscResource.Tests/issues/11
