### ISSUE TITLE
Missing "Scope" param for xFirewall

### ISSUE THREAD

**Issue by cydhaselton** [PowerShell/xNetworking#47]
Cannot specify a set of Remote and or Local IP addresses/subnets for the xFirewall configuration

**Comment by tysonjhayes** [comment]
Sorry I'm not that familiar with this configuration. Are you looking to specify RemoteMachine/RemoteAddress parameter for NetFirewalRule?


```powershell
-RemoteAddress<String[]>
Specifies that network packets with matching IP addresses match this rule. 
This parameter value is the second end point of an IPsec rule and specifies the computers that are subject to the requirements of this rule. 
This parameter value is an IPv4 or IPv6 address, hostname, subnet, range, or the following keyword: Any. 
The acceptable formats for this parameter are: 
-- Single IPv4 Address: 1.2.3.4 
-- Single IPv6 Address: fe80::1 
-- IPv4 Subnet (by network bit count): 1.2.3.4/24 
-- IPv6 Subnet (by network bit count): fe80::1/48 
-- IPv4 Subnet (by network mask): 1.2.3.4/255.255.255.0 
-- IPv4 Range: 1.2.3.4 through 1.2.3.7 
-- IPv6 Range: fe80::1 through fe80::9 
Note: Querying for rules with this parameter can only be performed using filter objects. See the Get-NetFirewallAddressFilter cmdlet for more information.

````

````powershell

-RemoteMachine<String>
Specifies that matching IPsec rules of the indicated computer accounts are created. 
This parameter specifies that only network packets that are authenticated as incoming from or outgoing to a computer identified in the list of computer accounts (SID) match this rule. This parameter value is specified as an SDDL string. 
Note: Querying for rules with this parameter can only be performed using filter objects. See the Get-NetFirewallSecurityFilter cmdlet for more information.

````

**Comment by cydhaselton** [comment]
Correct.  I am looking to specify the remote address/machine parameter for NetFirewallRule within DSC.  
I was looking for the parameter in xFirewall...is it in a different location?

**Comment by tysonjhayes** [comment]
I believe it should be in there, not sure why its not. It'll be a bit before I can spend some time looking at this and code up a solution.

I think it should be pretty straight forward. @PlagueHO might have time to get to this before I do but I'll try to get to it soon.

**Comment by PlagueHO** [comment]
I'll take a look when I do PR #44 - should be fairly straight forward! :+1: I'll take a look at these tonight if you like?

**Comment by tysonjhayes** [comment]
No rush on my account. Thanks!

**Comment by PlagueHO** [comment]
I've taken a look at this and @cydhaselton is quite right. These two parameters (RemoteAddress and RemoteUser) are missing from the resource (although partially supported in the ```Get-FirewallRuleProperty``` function).

I'm not sure why these are missing, but most likely because the resource initially was designed to support the most common parameters. Either that or it only supported the original rule parameters available on earlier versions of WFAS.

That being said, I can't see why they shouldn't be added and they're not particularly difficult parameters to add. So I'm happy to pop them in over the next few days if you're OK with that?

But while I'm at it I've noticed a few other parameters are missing. I don't think all of them need to be added at this time, but I will add a couple of them because they are related to RemoteMachine and RemoteAddress.

They missing parameters are (ones I think I should add now are in bold):
Authentication<Authentication>
DynamicTarget<DynamicTransport>
EdgeTraversalPolicy<EdgeTraversal>
Encryption<Encryption>
IcmpType<String[]>
InterfaceAlias<WildcardPattern[]>
InterfaceType<InterfaceType>
**LocalAddress<String[]>**
LocalOnlyMapping<Boolean>
**LocalUser<String>**
LooseSourceMapping<Boolean>
OverrideBlockRules<Boolean>
Owner<String>
Package<String>
Platform<String[]>
**RemoteAddress<String[]>**
**RemoteMachine<String>**
**RemoteUser<String>**

Any other parameters that don't get added could get logged in another issue so that they could be added later.

**Comment by cydhaselton** [comment]
Thanks for the speedy reply to this matter.
I can add the bolded parameters in a separate issue if it would help.

**Comment by PlagueHO** [comment]
I think it's all good. If @tysonjhayes is good with the changes I'll get them made and any properties I don't add I'll pop in a new Issue. I may find when I'm doing the change that adding additional ones don't really required much more effort. But thanks for the offer :+1:

**Comment by tysonjhayes** [comment]
Yup, my goal has always been to support every paramters we can. So let's get them all in. :+1:

**Comment by PlagueHO** [comment]
Cool! I'll get on it, starting wit ht ones @cydhaselton has requested (plus additional bolded ones) and any remaining put into an Issue so we can track them.

**Comment by tysonjhayes** [comment]
Howdy @cydhaselton, @PlagueHO has got some code in to address this. Could you check out the fixes and make sure they are working well for you?

**Comment by cydhaselton** [comment]
Hello @tysonjhayes.  I'll let my teammate know to pull the fixed module and test.  I'll update this issue with results.

Thanks, @PlagueHO  for your work!

**Comment by cydhaselton** [comment]
Hey @tysonjhayes and @PlagueHO.   This update is to let you know that that testing was successful.  Thanks again for all of your help...closing this issue.
