### ISSUE TITLE
[New Resource] Network Load Balancing

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#79]
Add [Network Load Balancing](https://technet.microsoft.com/en-us/library/ee817138.aspx) to the list of resources.

**Comment by PlagueHO** [comment]
I'm still of the thinking that because this would require at least 3 resources it might make more sense in it's own resource module. Also NLB is more closely related to clustering and requires the NLB feature installed and all the cmdlets live in the NetworkLoadBalancingClusters module rather than the Net module like all the other xNetworking stuff. Just my 2c. Forgive me if I've misunderstood the purpose of the resource.

**Comment by tysonjhayes** [comment]
Whoops you are right, I was just trying to open up some issues on them and wasn't paying that close attention.

**Comment by PlagueHO** [comment]
:+1: Would still be great to get this module somewhere though :)
